from __future__ import annotations

import asyncio
import logging
import random
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable

from claude_runner import run_apply
from git_pr import create_pull_request, get_changed_files, snapshot_changed_files
from models import FindingSummary
from store import apply_store

logger = logging.getLogger(__name__)

APPLY_SEMAPHORE = asyncio.Semaphore(1)

_SAMPLE_PROJECT_PATH = (Path(__file__).resolve().parent.parent / "sample_project").resolve()

# Must match CLAUDE_DIR_STAGING_PREFIX in frontend/src/utils/generatePrompt.ts
_STAGING_DIR = "_claude_optimize_staging"


def _is_sample_project(project_path: str) -> bool:
    try:
        return Path(project_path).resolve() == _SAMPLE_PROJECT_PATH
    except OSError:
        return False


async def _mock_apply(on_output: Callable[[str], None]) -> None:
    """Simulate a realistic Claude Code apply session without touching any files."""
    steps = [
        (0.4, "Reading project structure..."),
        (0.6, ""),
        (0.8, "Identified files to modify:"),
        (0.3, "  - src/api/client.ts"),
        (0.2, "  - src/services/claude.py"),
        (0.2, "  - src/utils/prompt.ts"),
        (0.7, ""),
        (1.0, "Applying prompt caching optimizations..."),
        (0.5, "  Adding cache_control headers to system prompts"),
        (0.8, "  Restructuring message array for cache efficiency"),
        (0.4, ""),
        (1.2, "Applying batching improvements..."),
        (0.5, "  Converting sequential API calls to batch requests"),
        (0.6, "  Added batch result aggregation"),
        (0.4, ""),
        (0.9, "Applying model selection optimizations..."),
        (0.5, "  Switching classification tasks to Haiku"),
        (0.4, "  Keeping complex reasoning on Sonnet"),
        (0.4, ""),
        (0.8, "Running validation checks..."),
        (0.6, "  All type checks passed"),
        (0.4, "  No breaking changes detected"),
        (0.5, ""),
        (0.3, "Done. Applied optimizations to 3 files."),
    ]

    for delay, line in steps:
        await asyncio.sleep(delay + random.uniform(-0.1, 0.15))
        on_output(line)


def _build_pr_title(summaries: list[FindingSummary]) -> str:
    """Build a concise PR title from finding titles."""
    if not summaries:
        return "Claude Optimize: Apply optimizations"

    # Use finding titles directly, truncating to fit ~72 chars
    prefix = "Claude Optimize: "
    max_len = 72 - len(prefix)
    titles: list[str] = []
    length = 0
    for s in summaries:
        title = s.title
        # Account for ", " separator between titles
        added_len = len(title) + (2 if titles else 0)
        if length + added_len > max_len and titles:
            remaining = len(summaries) - len(titles)
            if remaining == 1:
                titles.append(title)
            else:
                titles.append(f"+{remaining} more")
            break
        titles.append(title)
        length += added_len

    return prefix + ", ".join(titles)


def _build_pr_body(summaries: list[FindingSummary]) -> str:
    """Build a descriptive PR body from finding summaries."""
    lines: list[str] = []
    lines.append("## Summary")
    lines.append("")
    lines.append(
        f"This PR applies **{len(summaries)}** optimization(s) identified by "
        "[Claude Optimize](https://github.com/saharmor/claude-optimize), "
        "an automated tool that scans your codebase for Claude API and agentic SDK "
        "usage patterns and suggests improvements to reduce cost, latency, and "
        "improve reliability."
    )

    if summaries:
        lines.append("")
        lines.append("## Optimizations applied")
        for s in summaries:
            lines.append("")
            lines.append(f"### {s.title}")
            if s.file:
                lines.append(f"`{s.file}`")
            if s.description:
                lines.append("")
                lines.append(s.description)

            # Impact summary
            impacts: list[str] = []
            if s.cost_reduction in ("high", "medium"):
                impacts.append(f"**{s.cost_reduction.capitalize()}** cost reduction")
            if s.latency_reduction in ("high", "medium"):
                impacts.append(f"**{s.latency_reduction.capitalize()}** latency reduction")
            if s.reliability_improvement in ("high", "medium"):
                impacts.append(f"**{s.reliability_improvement.capitalize()}** reliability improvement")
            if impacts:
                lines.append("")
                lines.append("Expected impact: " + ", ".join(impacts))

            if s.docs_url:
                lines.append("")
                lines.append(f"[Read more in the docs]({s.docs_url})")

    lines.append("")
    lines.append("---")
    lines.append(
        "*Generated by [Claude Optimize](https://github.com/saharmor/claude-optimize). "
        "Claude Optimize is an open-source tool that analyzes how your project uses the "
        "Claude API and Anthropic's agentic SDKs, identifies optimization opportunities "
        "(prompt caching, batching, model selection, and more), and can automatically "
        "apply the recommended changes.*"
    )
    return "\n".join(lines)


async def run_apply_job(
    apply_id: str,
    prompt: str,
    project_path: str,
    finding_titles: list[str] | None = None,
    finding_files: list[str] | None = None,
    finding_docs_urls: list[str] | None = None,
    finding_summaries: list[FindingSummary] | None = None,
    scan_id: str | None = None,
) -> None:
    """Run Claude Code to apply selected findings to the project."""
    async with APPLY_SEMAPHORE:
        apply_store.update(apply_id, status="running", started_at=datetime.now(timezone.utc))
        apply_store.notify(apply_id, {
            "event": "apply_status",
            "data": {"status": "running"},
        })

        try:
            titles = finding_titles or []
            files = finding_files or []
            docs_urls = finding_docs_urls or []
            summaries = finding_summaries or []

            # Persist apply metadata and findings to SQLite
            summaries_json = [s.model_dump_json() for s in summaries]
            apply_store.persist_apply_metadata(
                apply_id,
                prompt_text=prompt,
                selection_count=len(titles),
                source_scan_run_id=scan_id,
            )
            if titles:
                apply_store.persist_apply_job_findings(
                    apply_id, titles, files, docs_urls, summaries_json,
                )
            apply_store.persist_apply_event(apply_id, "apply_started", {"status": "running"})
            # Map each finding file path to its index for fast lookup
            # Normalize to basename for matching (Claude may use absolute paths)
            file_to_indices: dict[str, list[int]] = {}
            for idx, fpath in enumerate(files):
                # Store both full path and basename for matching
                normalized = fpath.rstrip("/")
                file_to_indices.setdefault(normalized, []).append(idx)
                basename = normalized.rsplit("/", 1)[-1] if "/" in normalized else normalized
                if basename != normalized:
                    file_to_indices.setdefault(basename, []).append(idx)
                # Also register the staging path so tool_use events on
                # _claude_optimize_staging/... match .claude/... findings
                if normalized.startswith(".claude/"):
                    staged = _STAGING_DIR + "/" + normalized[len(".claude/"):]
                    file_to_indices.setdefault(staged, []).append(idx)

            completed_indices: set[int] = set()
            current_finding_index = -1

            def _on_tool_use(tool_name: str, file_path: str) -> None:
                """Called when Claude uses a file-editing tool. Match against findings."""
                nonlocal current_finding_index
                if not files:
                    return

                # Try matching by full path suffix or basename
                matched_idx: int | None = None
                normalized = file_path.rstrip("/")

                # Check all registered paths/basenames
                for key, indices in file_to_indices.items():
                    # Require a path-segment boundary match to avoid false positives
                    # (e.g. "foo.py" matching "bazfoo.py")
                    if (
                        normalized == key
                        or normalized.endswith("/" + key)
                        or key.endswith("/" + normalized)
                    ):
                        # Pick the first unfinished index for this file
                        for idx in indices:
                            if idx not in completed_indices:
                                matched_idx = idx
                                break
                        if matched_idx is not None:
                            break

                if matched_idx is None:
                    return

                # Mark previous finding as done (if different)
                if current_finding_index >= 0 and current_finding_index != matched_idx:
                    completed_indices.add(current_finding_index)
                    apply_store.notify(apply_id, {
                        "event": "finding_progress",
                        "data": {"index": current_finding_index, "status": "done"},
                    })
                    apply_store.update_apply_job_finding_status(apply_id, current_finding_index, "done")

                if matched_idx != current_finding_index:
                    current_finding_index = matched_idx
                    apply_store.notify(apply_id, {
                        "event": "finding_progress",
                        "data": {"index": matched_idx, "status": "applying"},
                    })
                    apply_store.update_apply_job_finding_status(apply_id, matched_idx, "applying")

            def on_output(line: str) -> None:
                apply_store.notify(apply_id, {
                    "event": "apply_output",
                    "data": {"line": line},
                })

            is_sample = _is_sample_project(project_path)

            # Snapshot dirty files BEFORE the apply so we can diff afterward
            files_before: set[str] = set()
            # Also snapshot directory contents for "create file" findings
            # (git may miss files in gitignored dirs like .claude/)
            dir_snapshots: dict[str, set[str]] = {}
            if not is_sample:
                files_before = await snapshot_changed_files(project_path)
                for fpath in files:
                    if fpath.endswith("/"):
                        dir_path = Path(project_path) / fpath
                        if dir_path.is_dir():
                            dir_snapshots[fpath] = {
                                str(p.relative_to(Path(project_path)))
                                for p in dir_path.rglob("*") if p.is_file()
                            }
                        else:
                            dir_snapshots[fpath] = set()

            if is_sample:
                await _mock_apply(on_output)
                # Simulate per-finding progress for sample project
                for idx in range(len(titles)):
                    apply_store.notify(apply_id, {
                        "event": "finding_progress",
                        "data": {"index": idx, "status": "done"},
                    })
                    apply_store.update_apply_job_finding_status(apply_id, idx, "done")
            else:
                await run_apply(
                    prompt, project_path,
                    on_output=on_output,
                    on_tool_use=_on_tool_use,
                )

            # Relocate files from the staging directory to .claude/
            # Claude Code blocks automated writes to .claude/, so the prompt
            # redirects those writes to _claude_optimize_staging/ instead.
            staging_dir = Path(project_path) / _STAGING_DIR
            if not is_sample and staging_dir.is_dir():
                target_dir = Path(project_path) / ".claude"
                for staged_file in staging_dir.rglob("*"):
                    if not staged_file.is_file():
                        continue
                    rel = staged_file.relative_to(staging_dir)
                    dest = target_dir / rel
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    shutil.move(str(staged_file), str(dest))
                    logger.info("Apply %s: relocated staged file %s -> %s", apply_id, rel, dest)
                    on_output(f"Moved {rel} to .claude/{rel}")
                # Clean up the staging directory
                shutil.rmtree(staging_dir, ignore_errors=True)

            # Compute changed files for both finding verification and PR creation
            changed_files: list[str] = []
            if not is_sample:
                changed_files = await get_changed_files(project_path, files_before)

                # Also check directory snapshots for new files (catches gitignored dirs)
                for dir_fpath, before_set in dir_snapshots.items():
                    dir_path = Path(project_path) / dir_fpath
                    if dir_path.is_dir():
                        after_set = {
                            str(p.relative_to(Path(project_path)))
                            for p in dir_path.rglob("*") if p.is_file()
                        }
                        new_files = after_set - before_set
                        for nf in new_files:
                            if nf not in changed_files:
                                changed_files.append(nf)

                logger.info(
                    "Apply %s: %d files changed: %s",
                    apply_id, len(changed_files), changed_files,
                )

            # Determine which findings were actually applied by checking changed files
            applied_indices: set[int] = set(completed_indices)
            for idx in range(len(files)):
                if idx in completed_indices:
                    continue
                finding_file = files[idx]
                actually_applied = False
                if finding_file and not is_sample:
                    finding_basename = finding_file.rstrip("/").rsplit("/", 1)[-1] if "/" in finding_file else finding_file.rstrip("/")
                    for cf in changed_files:
                        if cf == finding_file or cf.endswith(f"/{finding_file}") or cf.endswith(f"/{finding_basename}"):
                            actually_applied = True
                            break
                        # Also check if the changed file is inside a directory finding
                        if finding_file.endswith("/") and cf.startswith(finding_file):
                            actually_applied = True
                            break
                elif is_sample:
                    actually_applied = True

                if not actually_applied and finding_file:
                    title = titles[idx] if idx < len(titles) else "?"
                    logger.warning(
                        "Apply %s: finding %d (%s) not applied — expected file '%s' "
                        "but changed files were: %s",
                        apply_id, idx, title, finding_file, changed_files,
                    )

                if actually_applied:
                    applied_indices.add(idx)

                final_status = "done" if actually_applied else "skipped"
                apply_store.notify(apply_id, {
                    "event": "finding_progress",
                    "data": {"index": idx, "status": final_status},
                })
                apply_store.update_apply_job_finding_status(apply_id, idx, final_status)

            # Attempt to create a PR (skip for sample project and if nothing was applied)
            if not is_sample and applied_indices:
                apply_store.notify(apply_id, {
                    "event": "creating_pr",
                    "data": {"apply_id": apply_id},
                })
                on_output("")
                on_output("Creating pull request...")

                # Only include successfully applied findings in PR title/body
                applied_summaries = [
                    s for i, s in enumerate(summaries) if i in applied_indices
                ]
                branch_name = f"claude-optimize/{apply_id}"
                apply_store.update(apply_id, pr_branch=branch_name)
                pr_title = _build_pr_title(applied_summaries)
                pr_body = _build_pr_body(applied_summaries)

                try:
                    url = await create_pull_request(
                        project_path, branch_name, pr_title, pr_body,
                        changed_files=changed_files, on_output=on_output,
                    )
                    apply_store.update(apply_id, pr_url=url)
                    apply_store.notify(apply_id, {
                        "event": "pr_created",
                        "data": {"apply_id": apply_id, "pr_url": url},
                    })
                    apply_store.persist_apply_event(apply_id, "pr_created", {"pr_url": url})
                except Exception as pr_exc:
                    logger.warning("PR creation failed for %s: %s", apply_id, pr_exc)
                    apply_store.update(apply_id, pr_error=str(pr_exc))
                    apply_store.notify(apply_id, {
                        "event": "pr_failed",
                        "data": {"apply_id": apply_id, "error": str(pr_exc)},
                    })
                    apply_store.persist_apply_event(apply_id, "pr_failed", {"error": str(pr_exc)})

            apply_store.update(
                apply_id,
                status="completed",
                completed_at=datetime.now(timezone.utc),
            )
            apply_store.notify(apply_id, {
                "event": "apply_complete",
                "data": {"apply_id": apply_id, "status": "completed"},
            })
            apply_store.persist_apply_event(apply_id, "apply_complete", {"status": "completed"})
        except Exception as exc:
            logger.exception("Apply job %s failed", apply_id)
            apply_store.update(
                apply_id,
                status="failed",
                error=str(exc),
                completed_at=datetime.now(timezone.utc),
            )
            apply_store.notify(apply_id, {
                "event": "apply_failed",
                "data": {"apply_id": apply_id, "error": str(exc)},
            })
            apply_store.persist_apply_event(apply_id, "apply_failed", {"error": str(exc)})
        finally:
            apply = apply_store.get(apply_id)
            apply_store.notify(apply_id, {
                "event": "stream_complete",
                "data": {
                    "apply_id": apply_id,
                    "status": apply.status if apply else "failed",
                    "error": apply.error if apply else None,
                },
            })
